export const metadata = {
  title: "Online Booking | Le Soin",
  description: "Generated by create next app",
};
export default function ProjectLayout({ children, params }) {
  return (
    <div className="w-full bg-base-light-cream">
      <div className="px-5 max-w-[1200px] mx-auto">{children}</div>
    </div>
  );
}
