import Head from "next/head";
import React from "react";
import { notFound } from "next/navigation";
import { getSingleProduct } from "@/lib/products";

export const metadata = {
  title: `Search Result | Le Soin`,
  // description: "Generated by create next app",
};

export default function SearchLayout({ children, params, searchParams }) {
  return <div className="w-full bg-base-light-cream">{children}</div>;
}
