import Head from "next/head";
import React from "react";
import { notFound } from "next/navigation";
import { getSingleBlogData } from "@/lib/blogs";
import HTMLReactParser from "html-react-parser";

export async function generateMetadata({ params, searchParams }, parent) {
  // read route params
  const slug = params.slug;

  // fetch data
  const blog = await getSingleBlogData(slug);

  // // optionally access and extend (rather than replace) parent metadata
  // const previousImages = (await parent).openGraph?.images || [];

  // console.log(blog);
  if (!blog) notFound();

  // console.log(blog.title);
  return {
    title: `${HTMLReactParser(blog.title)} | Le Soin`,
    description: blog.short_content,
  };
}

export default function BlogLayout({ children, params }) {
  // const metadata = {
  //   title: params.slug,
  //   description: "Generated by create next app",
  // };
  return (
    <div className="w-full bg-base-light-cream">
      <div className="mx-auto max-w-[1200px] px-5">{children}</div>
    </div>
  );
}
