export const metadata = {
  title: "About Us | Le Soin",
  description: "Generated by create next app",
};
export default function ProjectLayout({ children, params }) {
  return (
    <div className="w-full bg-base-light-cream">
      <div className="mx-auto max-w-[1200px] px-5">{children}</div>
    </div>
  );
}
