import Head from "next/head";
import React from "react";
import { notFound } from "next/navigation";
import { getSingleProduct } from "@/lib/products";

export async function generateMetadata({ params, searchParams }, parent) {
  // read route params
  const slug = params.slug;

  // fetch data
  const product = await getSingleProduct(slug);

  // // optionally access and extend (rather than replace) parent metadata
  // const previousImages = (await parent).openGraph?.images || [];

  if (!product.slug) notFound();

  return {
    title: `${product.title} | Le Soin`,
    description: product.page_description,
  };
}

export default function ProjectLayout({ children, params }) {
  // const metadata = {
  //   title: params.slug,
  //   description: "Generated by create next app",
  // };
  return (
    <div className="w-full bg-base-light-cream">
      <div className="mx-auto max-w-[1200px] px-5">{children}</div>
    </div>
  );
}
